In [66]:
import numpy as np
import matplotlib.pyplot as plt
import cv2 

In [67]:
#Pergunta 1
img = np.array([[110,  35, 218, 19, 106],
                [232, 222, 159, 61,  13],
                [46,  148,  89, 31, 230],
                [67,  140, 131, 47, 241],
                [37,   37, 102, 61, 125]])*1.


print('Fracos :', (np.sum(img<94) - np.sum(img<62))/25)
print('Fortes :', np.sum(img>=94)/25)
print('Resposta é 1.2')

Fracos : 0.08
Fortes : 0.52
Resposta é 1.2


In [68]:
#Pergunta 2, apliquei a fórmula da última ficha
print('Resposta é 2.1')

Resposta é 2.1


In [69]:
#Pergunta 3
planoR = np.array([[58,58],[44,111]])
planoG = np.array([[79,110],[235,47]])
planoB = np.array([[231,112],[250,28]])

In [70]:
c1 = np.array([0.15,0.35])
c2 = np.array([0.60,0.25])

In [71]:
a = np.array([[200,50],[70,90]])
print(a.max())
a = (1.0/a.max()) 
a

200


0.005

In [72]:
#Pergunta 4, tem o maior valor da tabela
print('Resposta é 4.2')

Resposta é 4.2


In [73]:
#Pergunta 5
matriz = np.array([[193, 180, 210, 112, 125],
                 [189, 8, 177, 97, 114],
                 [100, 71, 81, 195, 165],
                 [167, 12, 242, 203, 181],
                 [44,25,9,48,192]])

print("Densidade de contornos:", np.sum(matriz>=70)/25)
print('Resposta é 5.2')

Densidade de contornos: 0.76
Resposta é 5.2


In [74]:
#Pergunta 6, são 8 previsões e errou 3 segundo a tabela
print('Probabildade de erro é ', 3/8)
print('Resposta é 6.4')

Probabildade de erro é  0.375
Resposta é 6.4


In [75]:
# Pergunta 7 (??)
print('Resposta é 7.3')

Resposta é 7.3


In [76]:
# Pergunta 8, ver slides tem um exemplo igual a explicar o pan right e left
print('Resposta é 8.1')

Resposta é 8.1


In [77]:
#Pergunta 9
t = np.array([[100, 102, 101],
                  [120, 120, 130],
                  [135, 130, 132]])

t1 = np.array([[ 90, 190,  95],
                  [115, 125, 203],
                  [140, 210, 195]])  

t2 = np.array([[101, 105, 115],
                  [150, 130, 135],
                  [145, 125, 210]])   


ts = np.array([[t], [t1], [t2]])

bg = np.median(ts, axis=0)
print(bg,'\n')
print('Resposta é 9.4')

[[[100. 105. 101.]
  [120. 125. 135.]
  [140. 130. 195.]]] 

Resposta é 9.4
